language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
    - sudo apt-get -y install libssl1.0-dev gcc make

install:
    - cpanm --quiet --notest Scalar::Util
    - cpanm --quiet --notest Net::DNS NetAddr::IP Mail::SpamAssassin Mail::AuthenticationResults

script:
   - HARNESS_IS_VERBOSE=1 prove -v -Ilib t

after_success:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cover -test -make 'prove -Ilib t' -report coveralls

#branches:
#  only:
#    - releases

before_install:
   - git config --global user.name "TravisCI"
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl
   - perl -V

